
# Syntax highlighting
markdown:            redcarpet
highlighter:         pygments

# Permalinks
permalink:           /:title
# relative_permalinks: true

# Setup
timezone:            Asia/Kolkata # eg. Asia/Kathmandu
locale:              en_us # eg. en_us
name:
title:               Zamindar
tagline:             'If you are on a path to loosing faith, continue ..'
description:         'About me'
url:                 http://nina07.github.io
rss:                 rss feed url
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                '/assets/images/nu.svg' #[best 300px X 300px]
disqus:              disqus_shortname # get it on https://disqus.com/admin/

author:
  name:           	 Niyanta
  url:            	 http://nina07.github.io
  facebook:          niyu.j
  twitter:           thats_nina07
  google_plus:       +NiyantaZamindar
  linkedin:          niyantazamindar
  quora:             Niyanta-Zamindar
  pinterest:         niyanta150792
  github:            nina07
fb_admins:           your facebook profile id
fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
